language: cpp

compiler: gcc

os: linux

dist: bionic

sudo: required

branches:
  only:
  - master
  - hodlrHmat

notifications:
  email:
    recipients:
      - liuyangzhuan@lbl.gov
    on_failure: always
    on_success: always
  slack:
    rooms:
      - ecpsparsesolvers:nBWC0jcAd7B1j9whHUYcaVJO
    on_failure: never
    on_success: never

env:
  jobs:
  - TEST_NUMBER=1
  - TEST_NUMBER=2
  - TEST_NUMBER=3
  - TEST_NUMBER=4
  - TEST_NUMBER=5
  - TEST_NUMBER=6
  - TEST_NUMBER=7
  - TEST_NUMBER=8
  - TEST_NUMBER=9
  - TEST_NUMBER=10
  - TEST_NUMBER=11
  - TEST_NUMBER=12
  - TEST_NUMBER=13
  - TEST_NUMBER=14
  - TEST_NUMBER=15
  - TEST_NUMBER=16
git:
  depth: 1

before_install:
  - export BLUE="\033[34;1m"
  - mkdir -p installDir

  - printf  "${BLUE} GC; Installing gcc-9 via apt\n"
  - sudo apt-get update
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-9 g++-9 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
  - export CXX="g++-9"
  - export CC="gcc-9"
  - printf "${BLUE} GC; Done installing gcc-9 via apt\n"

  - printf "${BLUE} GC; Installing gfortran via apt\n"
  - sudo apt-get install gfortran-9 -y
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-9 60
  - printf "${BLUE} GC; Done installing gfortran via apt\n"

  - printf "${BLUE} GC; Installing openmpi\n"
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - printf "${BLUE} GC; Done installing openmpi\n"
 
  - printf "${BLUE} GC; Installing dos2unixfrom apt\n"
  - sudo apt-get install dos2unix
  - printf "${BLUE} GC; Done installing dos2unixfrom apt\n"

  - printf "${BLUE} GC; Installing BLASfrom apt\n"
  - sudo apt-get install libblas-dev
  - export BLAS_LIB=/usr/lib/x86_64-linux-gnu/libblas.so
  - printf "${BLUE} GC; Done installing BLASfrom apt\n"

  - printf "${BLUE} GC; Installing LAPACKfrom apt\n"
  - sudo apt-get install liblapack-dev
  - export LAPACK_LIB=/usr/lib/x86_64-linux-gnu/liblapack.so
  - printf "${BLUE} GC; Done installing LAPACKfrom apt\n"

  - printf "${BLUE} GC; Installing ScaLAPACK from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - wget http://www.netlib.org/scalapack/scalapack-2.0.2.tgz
  - tar -xf scalapack-2.0.2.tgz
  - cd scalapack-2.0.2
  - rm -rf build
  - mkdir -p build
  - cd build
  - |
    cmake .. \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_Fortran_COMPILER=mpif90 \
    -DCMAKE_INSTALL_PREFIX=. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DCMAKE_Fortran_FLAGS="-fopenmp" \
    -DTPL_BLAS_LIBRARIES="$BLAS_LIB" \
    -DTPL_LAPACK_LIBRARIES="$LAPACK_LIB"
  - make
  - export SCALAPACK_LIB="$TRAVIS_BUILD_DIR/installDir/scalapack-2.0.2/build/lib/libscalapack.so"  
  - printf "${BLUE} GC; Done installing ScaLAPACK from source\n"

  
  - printf "${BLUE} GC; Installing ParMetis-4.0 from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz
  - tar -xf parmetis-4.0.3.tar.gz
  - cd parmetis-4.0.3/
  - mkdir -p install
  - make config shared=1 cc=mpicc cxx=mpic++ prefix=$PWD/install
  - make install > make_parmetis_install.log 2>&1
  - printf "${BLUE} GC; Done installing ParMetis-4.0 from source\n"
  
  - printf "${BLUE} GC; Installing arpack from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - git clone https://github.com/opencollab/arpack-ng.git
  - cd arpack-ng
  - rm -rf build
  - mkdir -p build
  - cd build
  - |
    cmake .. \
    -DBUILD_SHARED_LIBS=ON \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpic++ \
    -DCMAKE_Fortran_COMPILER=mpif90 \
    -DCMAKE_INSTALL_PREFIX=. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DCMAKE_Fortran_FLAGS="-fopenmp" \
    -DTPL_BLAS_LIBRARIES="$BLAS_LIB" \
    -DTPL_LAPACK_LIBRARIES="$LAPACK_LIB" \
    -DMPI=ON \
    -DEXAMPLES=ON \
    -DCOVERALLS=ON 
  - make
  - export ARPACK_LIB="$TRAVIS_BUILD_DIR/installDir/arpack-ng/build/lib/libarpack.so;$TRAVIS_BUILD_DIR/installDir/arpack-ng/build/lib/libparpack.so"
  - printf "${BLUE} GC; Done installing arpack from source\n"
  

install:
  - export BLUE="\033[34;1m"
  - printf "${BLUE} GC; Installing ButterflyPACK from source\n"
  - cd $TRAVIS_BUILD_DIR
  - rm -rf build
  - mkdir -p build
  - cd build
  - export CRAYPE_LINK_TYPE=dynamic
  - rm -rf CMakeCache.txt
  - rm -rf DartConfiguration.tcl
  - rm -rf CTestTestfile.cmake
  - rm -rf cmake_install.cmake
  - rm -rf CMakeFiles
  - |
    cmake .. \
    -DCMAKE_CXX_FLAGS="-fopenmp" \
    -Denable_blaslib=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpic++ \
    -DCMAKE_Fortran_COMPILER=mpif90 \
    -DCMAKE_INSTALL_PREFIX=. \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DCMAKE_Fortran_FLAGS="-fopenmp" \
    -DTPL_BLAS_LIBRARIES="$BLAS_LIB" \
    -DTPL_LAPACK_LIBRARIES="$LAPACK_LIB" \
    -DTPL_SCALAPACK_LIBRARIES="$SCALAPACK_LIB" \
    -DTPL_ARPACK_LIBRARIES="$ARPACK_LIB"
  - make
  - make install
  - printf "${BLUE} GC; Done installing ButterflyPACK from source\n"

script:
  - cd $TRAVIS_BUILD_DIR
  - travis_wait 80 sudo sh ./.travis_tests.sh
