language: cpp

compiler: gcc

os: linux

sudo: required

branches:
  only:
  - master

notifications:
  email: 
    recipients:
      - liuyangzhuan@lbl.gov
    on_failure: always
    on_success: always	  
  slack: 
    rooms:
      - ecpsparsesolvers:nBWC0jcAd7B1j9whHUYcaVJO
    on_failure: never
    on_success: never

env:
  matrix:
  - TEST_NUMBER=1"


git:
  depth: 1

before_install:
  - export BLUE="\033[34;1m"
  - mkdir -p installDir

  - printf  "${BLUE} GC; Installing gcc-6 via apt\n"
  - sudo apt-get update
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - export CXX="g++-6"
  - export CC="gcc-6"
  - printf "${BLUE} GC; Done installing gcc-6 via apt\n"

  - printf "${BLUE} GC; Installing gfortran via apt\n"
  - sudo apt-get install gfortran-6 -y
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 60
  - printf "${BLUE} GC; Done installing gfortran via apt\n"

  - printf "${BLUE} GC; Installing openmpi\n"
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - printf "${BLUE} GC; Done installing openmpi\n"

  - printf "${BLUE} GC; Installing dos2unixfrom apt\n"
  - sudo apt-get install dos2unix
  - printf "${BLUE} GC; Done installing dos2unixfrom apt\n"  
  
  - printf "${BLUE} GC; Installing BLASfrom apt\n"
  - sudo apt-get install libblas-dev
  - export BLAS_LIB=/usr/lib/libblas/libblas.so
  - printf "${BLUE} GC; Done installing BLASfrom apt\n"

  - printf "${BLUE} GC; Installing LAPACKfrom apt\n"
  - sudo apt-get install liblapack-dev
  - export LAPACK_LIB=/usr/lib/liblapack.so
  - printf "${BLUE} GC; Done installing LAPACKfrom apt\n"
  
  - printf "${BLUE} GC; Installing ScaLAPACK from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - wget http://www.netlib.org/scalapack/scalapack-2.0.2.tgz
  - tar -xf scalapack-2.0.2.tgz
  - cd scalapack-2.0.2
  - cp SLmake.inc.example SLmake.inc
  - sed -i "s/BLASLIB/#BLASLIB/" SLmake.inc
  - sed -i "s/LAPACKLIB/#LAPACKLIB/" SLmake.inc
  - sed -i "s/LIBS/#LIBS/" SLmake.inc
  - printf "BLASLIB=$BLAS_LIB\n" >> SLmake.inc
  - printf "LAPACKLIB=$LAPACK_LIB\n" >> SLmake.inc
  - printf "LIBS=$BLAS_LIB $LAPACK_LIB\n" >> SLmake.inc
  - sed -i "s/SCA#LAPACKLIB/#SCA#LAPACKLIB/" SLmake.inc
  - printf "SCALAPACKLIB=libscalapack.a\n" >> SLmake.inc
  - make lib  > tempMakeOutput.txt 2>&1
  - export SCALAPACK_LIB=$TRAVIS_BUILD_DIR/installDir/scalapack-2.0.2/libscalapack.a
  - printf "${BLUE} GC; Done installing ScaLAPACK from source\n"
  
  - printf "${BLUE} GC; Installing ParMetis-4.0 from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz
  - tar -xf parmetis-4.0.3.tar.gz
  - cd parmetis-4.0.3/
  - mkdir -p install
  - make config shared=1 cc=mpicc cxx=mpic++ prefix=$PWD/install
  - make install > make_parmetis_install.log 2>&1
  - printf "${BLUE} GC; Done installing ParMetis-4.0 from source\n"

install:
  - export BLUE="\033[34;1m"
  - printf "${BLUE} GC; Installing superlu_dist from source\n"
  - cd $TRAVIS_BUILD_DIR
  - rm -rf build
  - mkdir -p build
  - sh PrecisionPreprocessing.sh  
  - cd build 
  - export CRAYPE_LINK_TYPE=dynamic
  - rm -rf CMakeCache.txt
  - rm -rf DartConfiguration.tcl
  - rm -rf CTestTestfile.cmake
  - rm -rf cmake_install.cmake
  - rm -rf CMakeFiles
  - |
    cmake .. \
    -DCMAKE_CXX_FLAGS="-std=c++11 -O3 -fopenmp" \
    -Denable_blaslib=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_C_COMPILER=mpicc \
    -DCMAKE_CXX_COMPILER=mpic++ \
    -DCMAKE_Fortran_COMPILER=mpif90 \
    -DCMAKE_INSTALL_PREFIX=. \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
    -DCMAKE_Fortran_FLAGS="-cpp -DGNU -DPRNTlevel=0 -ftracer -funswitch-loops -ftree-vectorize -fimplicit-none -fno-range-check -ffree-line-length-none -ffixed-line-length-none -fopenmp " \
    -DTPL_LAPACK_LIBRARIES="$BLAS_LIB;$LAPACK_LIB" \
    -DTPL_SCALAPACK_LIBRARIES="$SCALAPACK_LIB"
  - make
  - make install
  - printf "${BLUE} GC; Done installing hodlrbf from source\n"

script: 
  - cd $TRAVIS_BUILD_DIR
  - ./.travis_tests.sh
