language: cpp

compiler: gcc

os: linux

sudo: required

branches:
  only:
  - master

notifications:
  email: 
    recipients:
      - liuyangzhuan@lbl.gov
    on_failure: always
    on_success: always	  
  slack: 
    rooms:
      - ecpsparsesolvers:nBWC0jcAd7B1j9whHUYcaVJO
    on_failure: never
    on_success: never

env:
  matrix:
  - TEST_NUMBER=1"


git:
  depth: 1

before_install:
  - export BLUE="\033[34;1m"
  - mkdir -p installDir

  - printf  "${BLUE} GC; Installing gcc-6 via apt\n"
  - sudo apt-get update
  - sudo apt-get install build-essential software-properties-common -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - export CXX="g++-6"
  - export CC="gcc-6"
  - printf "${BLUE} GC; Done installing gcc-6 via apt\n"

  - printf "${BLUE} GC; Installing gfortran via apt\n"
  - sudo apt-get install gfortran-6 -y
  - sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-6 60
  - printf "${BLUE} GC; Done installing gfortran via apt\n"

  - printf "${BLUE} GC; Installing openmpi\n"
  - sudo apt-get install openmpi-bin libopenmpi-dev
  - printf "${BLUE} GC; Done installing openmpi\n"

  - printf "${BLUE} GC; Installing BLASfrom apt\n"
  - sudo apt-get install libblas-dev
  - export BLAS_LIB=/usr/lib/libblas/libblas.so
  - printf "${BLUE} GC; Done installing BLASfrom apt\n"

  - printf "${BLUE} GC; Installing LAPACKfrom apt\n"
  - sudo apt-get install liblapack-dev
  - export LAPACK_LIB=/usr/lib/liblapack.so
  - printf "${BLUE} GC; Done installing LAPACKfrom apt\n"
  
  - printf "${BLUE} GC; Installing SCALAPACKfrom apt\n"
  - sudo apt-get install libscalapack-mpi-dev
  - export SCALAPACK_LIB=/usr/lib/libscalapack.so
  - printf "${BLUE} GC; Done installing SCALAPACKfrom apt\n"  
  
  - printf "${BLUE} GC; Installing ParMetis-4.0 from source\n"
  - cd $TRAVIS_BUILD_DIR/installDir
  - wget http://glaros.dtc.umn.edu/gkhome/fetch/sw/parmetis/parmetis-4.0.3.tar.gz
  - tar -xf parmetis-4.0.3.tar.gz
  - cd parmetis-4.0.3/
  - mkdir -p install
  - make config shared=1 cc=mpicc cxx=mpic++ prefix=$PWD/install
  - make install > make_parmetis_install.log 2>&1
  - printf "${BLUE} GC; Done installing ParMetis-4.0 from source\n"

install:
  - export BLUE="\033[34;1m"
  - printf "${BLUE} GC; Installing superlu_dist from source\n"
  - cd $TRAVIS_BUILD_DIR
  - cd build 
  - ./run_cmake_build_gnu_ubuntu.sh
  - make
  - make install
  - printf "${BLUE} GC; Done installing hodlrbf from source\n"

script: 
  - cd $TRAVIS_BUILD_DIR
  - ./.travis_tests.sh
